### ISSUE TITLE
Per-page wording, misspellings, broken links, etc

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/old-documentation#49]
I'll do my best to keep this list readable, I think it's a bit more manageable to keep it all in one place but let me know if I should open several issues instead.

Most of the feedback is about minor inconsistencies and misspellings, but some of it is mostly my opinion. I'll try to highlight those, you can do with it what you think is best.

# Feedback

https://docs.decentraland.org/documentation/introduction/
- thru -> through (thru is only for informal communication)

- speed up development times -> speed up development **time**

https://docs.decentraland.org/documentation/create-scene/
- In Decentraland, a scene is the representation of the content of in an estate/LAND => what does `the content *of in an* estate/LAND` mean?

- Type Script scenes => **TypeScript** scenes

- end users of your parsel will see => end users of your **parcel** will see

- The only thing it really does is => _Opinion_ This is a weird way to phrase it. Maybe **It really just...** ?

- To preview your rendered scene locally (without uploading it to IPFS) => _Opinion_  This is the first time IPFS is mentioned, confusing for the uninitiated. I started from developers.decentraland.org which took me to `Building scenes-> Introduction`. Maybe a link to https://docs.decentraland.org/decentraland/ or to https://docs.decentraland.org/documentation/publishing/#what-is-ipfs ?

- To edit a scene, we recommend using an IDE like Visual Studio Code. => VSCode isn’t really an IDE

- Next Step: Decentraland Introduction => Is that ok?

https://docs.decentraland.org/documentation/publishing/
- Your scene complies with all of the scene limitations => Broken link
- Otherwise you can purchase LAND in the Market => Broken link
- Note:  => are those necessary? the indented block already serves as a “Note:” and was not there before
- Advanced samples => Examples have links without capitalisation

https://docs.decentraland.org/documentation/mvp-guidelines/
- Next Step => Takes me to `Scene limitations`, is that ok?

- _Opinion_ This was a bit of a surprise. Reading from top to bottom I expected to find information about how the SDK worked and not how should I build an MVP. Not saying it's useless information, just the placement seemed weird. Also the reference to the `persistent core loop` when the docs told me there wasn’t any loop before threw me off.

https://docs.decentraland.org/sdk-reference/SDK-Overview/
- Locally-run scenes - or dynamic => or? dynamic. It doesn’t say static anywhere. (same with Remotely-run)

- For additional terms, definitions, and explanations, please refer to our complete Glossary. => Broken link

- the SDK, please refer to the \*\*SDK Quick Start Guide\*\* => are the asterisks necessary?

- please read our SDK Quick Start Guide or the CLI Tutorial => CLI Tutorial is a broken link

- Next Step => Not the same as the sidebar again. Won't point this out again.

https://docs.decentraland.org/sdk-reference/scene-content-guide/
- Tip: When editing the code via a IDE (like Visual Studio Code) => VSCode is not an IDE

- Transition code example:  `<box rotation={currnetRotation}` => **currentRotation***

- Another code example: `<box rotation={currnetRotation} color={currnetColor} scale={currnetScale}` => **current***

- Materials are also implicitly imported into a scene when you import a gtLF => should be **glTF** ?

- This is useful, for example, to verify that animations are properly attached and their names. => and their names what?

- _Question_: Why is the sound property a string instead of an object?

- When using the liner or exponential model => **linear***

- Entities that have collision disabled can walked through => can **be** walked through ?

- In Entity Collisions the code snippet says `ignoreCollisions="false”`, shouldn’t it be `ignoreCollisions={false}` (it’s not xml) ?

- Decentralan currently doesn’t have a physics engine => **Decentraland***

- No Next Step

https://docs.decentraland.org/sdk-reference/event-handling/
- The **The click event** example shows that `this.setState` is a synchronous operation, this differs from React and confused me a bit. Should this be on a callback?

- A simpler way to deal with clicks that are done on a single entity => A simpler way to deal with clicks *made* on a single entity ?

- Note:Entity-specific => missing space after **Note:**

- **Entity-specific click events**
    - `this.eventSubscriber.on('redButton_click', ()) => {` => Syntax error on `()) =>`
    - missing `;` at the end of the call

- **Pointer down and pointer up**
    - Class name is not PascalCased
    - `buttonState` starts as false instead of `0`

- **Rotation change** 
    - `state = { rotation: { x: 0, y: 0, z: 0 }}` missing space between curly braces at the end `}}`
    - `this.state.rotation.x +=  90 ; ` you can set the state directly?? https://docs.decentraland.org/sdk-reference/scene-state/ says to never do it.
    - Extra space at the end of the above statement

- **General** missing `;` in all import statements

https://docs.decentraland.org/sdk-reference/scene-state/
- **Set the state** code example indented strangely

- The only exception to this is if the `shouldSceneUpdate()` function is set up to prevent. => to prevent **it*** ?

- **Reference the state** code example indented strangely

- the `render()` method draws a dynamic scene where the position of an entity is based on a variable in the status => of an entity is based on a variable in the **state***

https://docs.decentraland.org/sdk-reference/entity-interfaces/
- or include the ignoreCollision component to change how it reponds to collisions with other entities => wasn’t `ignoreCollision` an attribute/property?

- Same comment as above about VSCode

- **Box** this is the only code example where the position looks like this: `{ { x: 5, y: 0, z: 2 } }` instead of `{{ x: 5, y: 0, z: 2 }}`

- **Base Entity**
    - First code example: `scale={{ x: 2, y: 2, z: 0.0  5 }}` five on the loose!

- **Materials** this is the only Interface definition that doesn’t have newlines between properties

https://docs.decentraland.org/sdk-reference/scriptable-scene/
- **Lifecycle methods**
    - The class on the code sample is missing the state declaration. There are floating properties  `eventSubscriber: EventSubscriber; timer: number; state: State = { counter: 0 }`
    - Where does `EventSubscriber` come from?
    - `sceneDidMount` has lingering asterisks on the comment
    - maybe just return `this.state.counter < 20` on `shouldSceneUpdate` ?
    - The summarized steps change the font size on the 4th item

- **Low-level API**
    - Once the class is created, it requires an instance of EntityController to the host (…) => requires an instance **from*** the host?
    - (…) (the engine) , this is an asynchronous call. => there a space before the comma
	
https://docs.decentraland.org/documentation/scene-limitations/
- thru -> through (thru is only for informal communication)

- Using Blender Render, any of its shaders are supported, that includes diffuse, specular, transparency, etc => **all*** of its shaders are supported ?

[General](https://docs.decentraland.org/)
- Next Step and Related documents -> Maybe **Related Documents** should be to the left and **Next Step** to the right? I think that it follows what I'm reading better, as is indented to the right. Maybe capitalise documents or lowercase Step?

- XML/React like Code in the SDK Entity interfaces (https://docs.decentraland.org/sdk-reference/entity-interfaces/) looks a lot better than in Scene Content guide (https://docs.decentraland.org/sdk-reference/scene-content-guide/) probably because of the language set for the syntax highlighting

- Sometimes it says `export interface myState` and others `export interface IProps`. The naming is kind of confusing

- Visual error:
<img src="https://user-images.githubusercontent.com/692077/42691275-a4c73c6c-86a7-11e8-846d-599cbf6dce9f.png" width="200" />

**Comment by nearnshaw** [comment]
Thanks @NicoSantangelo 

I got up to "event handling" so far, I'm working on a separate branch for now

Some comments on what I've gone over so far:
- I'm not sure why the links you found are broken, the code looks fine but they don't work. I need to investigate
- "thru": yes it's less formal than through, but that's how we want to sound, we want the docs to have an approachable and friendly voice
- "speed up development times": although that might be a bit grammatically weird, it is a common way to say it
-"Note:" :   they are a bit redundant today, but we plan to have a more robust tool for publishing in the future that would distinguish comments with Note / Tip / Warning and show them in different colors.
-"Next Step":Yeah, several of those don't make sense, that's something I need to revise well in the future
- MVP Guidelines:  Yes, the reason why that article appears to be out of place is because it was written as something for the Districts and then we added it in here because there was no better place to publish it.  Nevertheless, since it's in the "Building Scenes" section (not in the SDK Reference section), it's not all that bad. In the future we'll want to reshape this doc so that it's more useful.

**Comment by abarmat** [comment]
I see that in some places in the docs what should be tag **attributes** are being called components:

Example:
```
 <box 
    rotation={currnetRotation}
    color={currnetColor}
    scale={currnetScale}
    transition={ 
```
Rotation component => Rotation attribute

Reference: https://docs.decentraland.org/sdk-reference/scene-content-guide/

**Comment by nearnshaw** [comment]
@abarmat that's something we need to discuss, we need to have consistent terminology. It's difficult because there's a clash between multiple things:
-  XML lens: those things are, as you say, attributes
- Entity / Component model lens: The tag ( "box" in your example) is an entity, and each of its attributes is a component.   (https://en.wikipedia.org/wiki/Entity%E2%80%93component%E2%80%93system)
- React.js lens: the tag (the "box" in your example) is called a "component", not sure how the attributes would be called there, maybe "properties"?.

It's something I've been thinking about while I write, but I'm not very happy with how we're using these terms, we need to come up with terminology that fits all of these perspectives with the least amount of noise.

**Comment by nearnshaw** [comment]
@NicoSantangelo 
Re: on "The The click event example shows that this.setState is a synchronous operation, this differs from React and confused me a bit. Should this be on a callback?"
this.setState is being run as part of a subscribeTo, which is an event handler that runs asynchronously.
I'm not all that familiar with React, so I'm not sure how it differs. How would you make that clearer for React users?

Re: on the what side to put Next Step vs Related Documents: agreed, we will soon start working with Mat on redesigning the docs page to enable several features we need. This should be amongst the requirements

Re: on the visual error on the screenshot:
I couldn't reproduce that, I tried zooming in and out of the page and couldn't get it to break. How did you get to see it like that?

Re: on "Sometimes it says export interface myState and others export interface IProps. The naming is kind of confusing"
The naming is different because they are two separate things. I use myState when declaring a scene state, and IProps when declaring the properties for a custom type of entity. State and properties are similar things, but they are meant to be used differently: the state for things that change locally, the properties for information that's inherited from parents.
On the other hand, most code samples outside the docs use IState rather than myState, and it would make sense to make it consistent with that, so I'll change myState to IState.
